name: CI

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 2 2 */4 *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    name: Build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - uses: borales/actions-yarn@v4
        with:
          cmd: install
      - uses: borales/actions-yarn@v4
        with:
          cmd: run lint
      - uses: borales/actions-yarn@v4
        with:
          cmd: run build
